class UVO_voice_WEST {
	name = "WEST";
	factions[] = {};

	class events {
		calloutsN[] = {
			QGVAR(calloutN01_WEST),
			QGVAR(calloutN02_WEST),
			QGVAR(calloutN03_WEST),
			QGVAR(calloutN04_WEST),
			QGVAR(calloutN05_WEST),
			QGVAR(calloutN06_WEST)
		};
		calloutsNE[] = {
			QGVAR(calloutNE01_WEST),
			QGVAR(calloutNE02_WEST),
			QGVAR(calloutNE03_WEST),
			QGVAR(calloutNE04_WEST),
			QGVAR(calloutNE05_WEST),
			QGVAR(calloutNE06_WEST)
		};
		calloutsE[] = {
			QGVAR(calloutE01_WEST),
			QGVAR(calloutE02_WEST),
			QGVAR(calloutE03_WEST),
			QGVAR(calloutE04_WEST),
			QGVAR(calloutE05_WEST),
			QGVAR(calloutE06_WEST)
		};
		calloutsSE[] = {
			QGVAR(calloutSE01_WEST),
			QGVAR(calloutSE02_WEST),
			QGVAR(calloutSE03_WEST),
			QGVAR(calloutSE04_WEST),
			QGVAR(calloutSE05_WEST),
			QGVAR(calloutSE06_WEST)
		};
		calloutsS[] = {
			QGVAR(calloutS01_WEST),
			QGVAR(calloutS02_WEST),
			QGVAR(calloutS03_WEST),
			QGVAR(calloutS04_WEST),
			QGVAR(calloutS05_WEST),
			QGVAR(calloutS06_WEST)
		};
		calloutsSW[] = {
			QGVAR(calloutSW01_WEST),
			QGVAR(calloutSW02_WEST),
			QGVAR(calloutSW03_WEST),
			QGVAR(calloutSW04_WEST),
			QGVAR(calloutSW05_WEST),
			QGVAR(calloutSW06_WEST)
		};
		calloutsW[] = {
			QGVAR(calloutW01_WEST),
			QGVAR(calloutW02_WEST),
			QGVAR(calloutW03_WEST),
			QGVAR(calloutW04_WEST),
			QGVAR(calloutW05_WEST),
			QGVAR(calloutW06_WEST)
		};
		calloutsNW[] = {
			QGVAR(calloutNW01_WEST),
			QGVAR(calloutNW02_WEST),
			QGVAR(calloutNW03_WEST),
			QGVAR(calloutNW04_WEST),
			QGVAR(calloutNW05_WEST),
			QGVAR(calloutNW06_WEST)
		};
		explosive[] = {
			QGVAR(explosive01_WEST),
			QGVAR(explosive02_WEST),
			QGVAR(explosive03_WEST),
			QGVAR(explosive04_WEST),
			QGVAR(explosive05_WEST),
			QGVAR(explosive06_WEST),
			QGVAR(explosive07_WEST),
			QGVAR(explosive08_WEST),
			QGVAR(explosive09_WEST),
			QGVAR(explosive10_WEST),
			QGVAR(explosive11_WEST),
			QGVAR(explosive12_WEST),
			QGVAR(explosive13_WEST),
			QGVAR(explosive14_WEST)
		};
		flash[] = {
			QGVAR(flash01_WEST),
			QGVAR(flash02_WEST),
			QGVAR(flash03_WEST),
			QGVAR(flash04_WEST),
			QGVAR(flash05_WEST),
			QGVAR(flash06_WEST),
			QGVAR(flash07_WEST)
		};
		frag[] = {
			QGVAR(frag01_WEST),
			QGVAR(frag02_WEST),
			QGVAR(frag03_WEST),
			QGVAR(frag04_WEST),
			QGVAR(frag05_WEST),
			QGVAR(frag06_WEST),
			QGVAR(frag07_WEST),
			QGVAR(frag08_WEST),
			QGVAR(frag09_WEST),
			QGVAR(frag10_WEST),
			QGVAR(frag11_WEST),
			QGVAR(frag12_WEST),
			QGVAR(frag13_WEST),
			QGVAR(frag14_WEST)
		};
		incendiary[] = {
			QGVAR(incendiary01_WEST),
			QGVAR(incendiary02_WEST),
			QGVAR(incendiary03_WEST),
			QGVAR(incendiary04_WEST),
			QGVAR(incendiary05_WEST),
			QGVAR(incendiary06_WEST),
			QGVAR(incendiary07_WEST)
		};
		smoke[] = {
			QGVAR(smoke01_WEST),
			QGVAR(smoke02_WEST),
			QGVAR(smoke03_WEST),
			QGVAR(smoke04_WEST),
			QGVAR(smoke05_WEST),
			QGVAR(smoke06_WEST),
			QGVAR(smoke07_WEST),
			QGVAR(smoke08_WEST),
			QGVAR(smoke09_WEST)
		};
		spotNade[] = {
			QGVAR(spotNade01_WEST),
			QGVAR(spotNade02_WEST),
			QGVAR(spotNade03_WEST),
			QGVAR(spotNade04_WEST),
			QGVAR(spotNade05_WEST),
			QGVAR(spotNade06_WEST),
			QGVAR(spotNade07_WEST),
			QGVAR(spotNade08_WEST),
			QGVAR(spotNade09_WEST),
			QGVAR(spotNade10_WEST),
			QGVAR(spotNade11_WEST),
			QGVAR(spotNade12_WEST),
			QGVAR(spotNade13_WEST),
			QGVAR(spotNade14_WEST),
			QGVAR(spotNade15_WEST),
			QGVAR(spotNade16_WEST),
			QGVAR(spotNade17_WEST),
			QGVAR(spotNade18_WEST),
			QGVAR(spotNade19_WEST),
			QGVAR(spotNade20_WEST)
		};
		friendlyFire[] = {
			QGVAR(friendlyFire01_WEST),
			QGVAR(friendlyFire02_WEST),
			QGVAR(friendlyFire03_WEST),
			QGVAR(friendlyFire04_WEST),
			QGVAR(friendlyFire05_WEST),
			QGVAR(friendlyFire06_WEST),
			QGVAR(friendlyFire07_WEST),
			QGVAR(friendlyFire08_WEST),
			QGVAR(friendlyFire09_WEST),
			QGVAR(friendlyFire10_WEST),
			QGVAR(friendlyFire11_WEST),
			QGVAR(friendlyFire12_WEST),
			QGVAR(friendlyFire13_WEST),
			QGVAR(friendlyFire14_WEST),
			QGVAR(friendlyFire15_WEST)
		};
		wounded[] = {
			QGVAR(wounded01_WEST),
			QGVAR(wounded02_WEST),
			QGVAR(wounded03_WEST),
			QGVAR(wounded04_WEST),
			QGVAR(wounded05_WEST),
			QGVAR(wounded06_WEST),
			QGVAR(wounded07_WEST),
			QGVAR(wounded08_WEST),
			QGVAR(wounded09_WEST),
			QGVAR(wounded10_WEST),
			QGVAR(wounded11_WEST),
			QGVAR(wounded12_WEST),
			QGVAR(wounded13_WEST),
			QGVAR(wounded14_WEST),
			QGVAR(wounded15_WEST),
			QGVAR(wounded16_WEST),
			QGVAR(wounded17_WEST),
			QGVAR(wounded18_WEST),
			QGVAR(wounded19_WEST),
			QGVAR(wounded20_WEST),
			QGVAR(wounded21_WEST),
			QGVAR(wounded22_WEST),
			QGVAR(wounded23_WEST),
			QGVAR(wounded24_WEST),
			QGVAR(wounded25_WEST),
			QGVAR(wounded26_WEST),
			QGVAR(wounded27_WEST),
			QGVAR(wounded28_WEST),
			QGVAR(wounded29_WEST),
			QGVAR(wounded30_WEST)
		};
		allyDown[] = {
			QGVAR(allyDown01_WEST),
			QGVAR(allyDown02_WEST),
			QGVAR(allyDown03_WEST),
			QGVAR(allyDown04_WEST),
			QGVAR(allyDown05_WEST),
			QGVAR(allyDown06_WEST),
			QGVAR(allyDown07_WEST),
			QGVAR(allyDown08_WEST),
			QGVAR(allyDown09_WEST),
			QGVAR(allyDown10_WEST),
			QGVAR(allyDown11_WEST),
			QGVAR(allyDown12_WEST),
			QGVAR(allyDown13_WEST),
			QGVAR(allyDown14_WEST),
			QGVAR(allyDown15_WEST),
			QGVAR(allyDown16_WEST),
			QGVAR(allyDown17_WEST),
			QGVAR(allyDown18_WEST),
			QGVAR(allyDown19_WEST),
			QGVAR(allyDown20_WEST),
			QGVAR(allyDown21_WEST),
			QGVAR(allyDown22_WEST),
			QGVAR(allyDown23_WEST),
			QGVAR(allyDown24_WEST),
			QGVAR(allyDown25_WEST),
			QGVAR(allyDown26_WEST),
			QGVAR(allyDown26_WEST),
			QGVAR(allyDown27_WEST),
			QGVAR(allyDown28_WEST),
			QGVAR(allyDown29_WEST),
			QGVAR(allyDown30_WEST),
			QGVAR(allyDown31_WEST),
			QGVAR(allyDown32_WEST),
			QGVAR(allyDown33_WEST),
			QGVAR(allyDown34_WEST),
			QGVAR(allyDown35_WEST)
		};
		targDownHi[] = {
			QGVAR(targDownHi01_WEST),
			QGVAR(targDownHi02_WEST),
			QGVAR(targDownHi03_WEST),
			QGVAR(targDownHi04_WEST),
			QGVAR(targDownHi05_WEST),
			QGVAR(targDownHi06_WEST),
			QGVAR(targDownHi07_WEST),
			QGVAR(targDownHi08_WEST),
			QGVAR(targDownHi09_WEST),
			QGVAR(targDownHi10_WEST),
			QGVAR(targDownHi11_WEST),
			QGVAR(targDownHi12_WEST),
			QGVAR(targDownHi13_WEST)
		};
		targDownLo[] = {
			QGVAR(targDownLo01_WEST),
			QGVAR(targDownLo02_WEST),
			QGVAR(targDownLo03_WEST),
			QGVAR(targDownLo04_WEST),
			QGVAR(targDownLo05_WEST),
			QGVAR(targDownLo06_WEST),
			QGVAR(targDownLo07_WEST),
			QGVAR(targDownLo08_WEST),
			QGVAR(targDownLo09_WEST),
			QGVAR(targDownLo10_WEST)
		};
		cover[] = {
			QGVAR(cover01_WEST),
			QGVAR(cover02_WEST),
			QGVAR(cover03_WEST),
			QGVAR(cover04_WEST),
			QGVAR(cover05_WEST),
			QGVAR(cover06_WEST),
			QGVAR(cover07_WEST),
			QGVAR(cover08_WEST),
			QGVAR(cover09_WEST),
			QGVAR(cover10_WEST),
			QGVAR(cover11_WEST),
			QGVAR(cover12_WEST),
			QGVAR(cover13_WEST),
			QGVAR(cover14_WEST),
			QGVAR(cover15_WEST),
			QGVAR(cover16_WEST),
			QGVAR(cover17_WEST),
			QGVAR(cover18_WEST)
		};
		ammoLow[] = {
			QGVAR(ammolow01_WEST),
			QGVAR(ammolow02_WEST),
			QGVAR(ammolow03_WEST),
			QGVAR(ammolow04_WEST),
			QGVAR(ammolow05_WEST),
			QGVAR(ammolow06_WEST)
		};
		reloading[] = {
			QGVAR(reloading01_WEST),
			QGVAR(reloading02_WEST),
			QGVAR(reloading03_WEST),
			QGVAR(reloading04_WEST),
			QGVAR(reloading05_WEST),
			QGVAR(reloading06_WEST),
			QGVAR(reloading07_WEST),
			QGVAR(reloading08_WEST),
			QGVAR(reloading09_WEST),
			QGVAR(reloading10_WEST),
			QGVAR(reloading11_WEST),
			QGVAR(reloading12_WEST),
			QGVAR(reloading13_WEST),
			QGVAR(reloading14_WEST),
			QGVAR(reloading15_WEST),
			QGVAR(reloading16_WEST),
			QGVAR(reloading17_WEST),
			QGVAR(reloading18_WEST),
			QGVAR(reloading19_WEST),
			QGVAR(reloading20_WEST),
			QGVAR(reloading21_WEST),
			QGVAR(reloading22_WEST),
			QGVAR(reloading23_WEST),
			QGVAR(reloading24_WEST),
			QGVAR(reloading25_WEST),
			QGVAR(reloading26_WEST),
			QGVAR(reloading27_WEST),
			QGVAR(reloading28_WEST),
			QGVAR(reloading29_WEST),
			QGVAR(reloading30_WEST),
			QGVAR(reloading31_WEST)
		};
		rocketSuppression[] = {
			QGVAR(rpg01_WEST),
			QGVAR(rpg02_WEST),
			QGVAR(rpg03_WEST),
			QGVAR(rpg04_WEST),
			QGVAR(rpg05_WEST),
			QGVAR(rpg06_WEST),
			QGVAR(rpg07_WEST),
			QGVAR(rpg08_WEST),
			QGVAR(rpg09_WEST)
		};
		bulletSuppression[] = {
			QGVAR(suppressed01_WEST),
			QGVAR(suppressed02_WEST),
			QGVAR(suppressed03_WEST),
			QGVAR(suppressed04_WEST),
			QGVAR(suppressed05_WEST),
			QGVAR(suppressed06_WEST),
			QGVAR(suppressed07_WEST),
			QGVAR(suppressed08_WEST),
			QGVAR(suppressed09_WEST),
			QGVAR(suppressed10_WEST),
			QGVAR(suppressed11_WEST),
			QGVAR(suppressed12_WEST),
			QGVAR(suppressed13_WEST),
			QGVAR(suppressed14_WEST),
			QGVAR(suppressed15_WEST),
			QGVAR(suppressed16_WEST),
			QGVAR(suppressed17_WEST),
			QGVAR(suppressed18_WEST),
			QGVAR(suppressed19_WEST),
			QGVAR(suppressed20_WEST),
			QGVAR(suppressed21_WEST),
			QGVAR(suppressed22_WEST),
			QGVAR(suppressed23_WEST),
			QGVAR(suppressed24_WEST),
			QGVAR(suppressed25_WEST),
			QGVAR(suppressed26_WEST),
			QGVAR(suppressed27_WEST),
			QGVAR(suppressed28_WEST),
			QGVAR(suppressed29_WEST),
			QGVAR(suppressed30_WEST),
			QGVAR(suppressed31_WEST),
			QGVAR(suppressed32_WEST)
		};
		death[] = {};
	};
};
