class UVO_voice_GUER {
	name = "GUER";
	factions[] = {};

	class events {
		calloutsN[] = {
			QGVAR(calloutN01_GUER),
			QGVAR(calloutN02_GUER),
			QGVAR(calloutN03_GUER)
		};
		calloutsNE[] = {
			QGVAR(calloutNE01_GUER),
			QGVAR(calloutNE02_GUER),
			QGVAR(calloutNE03_GUER)
		};
		calloutsE[] = {
			QGVAR(calloutE01_GUER),
			QGVAR(calloutE02_GUER),
			QGVAR(calloutE03_GUER)
		};
		calloutsSE[] = {
			QGVAR(calloutSE01_GUER),
			QGVAR(calloutSE02_GUER),
			QGVAR(calloutSE03_GUER)
		};
		calloutsS[] = {
			QGVAR(calloutS01_GUER),
			QGVAR(calloutS02_GUER),
			QGVAR(calloutS03_GUER)
		};
		calloutsSW[] = {
			QGVAR(calloutSW01_GUER),
			QGVAR(calloutSW02_GUER),
			QGVAR(calloutSW03_GUER)
		};
		calloutsW[] = {
			QGVAR(calloutW01_GUER),
			QGVAR(calloutW02_GUER),
			QGVAR(calloutW03_GUER)
		};
		calloutsNW[] = {
			QGVAR(calloutNW01_GUER),
			QGVAR(calloutNW02_GUER),
			QGVAR(calloutNW03_GUER)
		};
		frag[] = {
			QGVAR(frag01_GUER),
			QGVAR(frag02_GUER),
			QGVAR(frag03_GUER),
			QGVAR(frag04_GUER),
			QGVAR(frag05_GUER),
			QGVAR(frag06_GUER),
			QGVAR(frag07_GUER),
			QGVAR(frag08_GUER),
			QGVAR(frag09_GUER),
			QGVAR(frag10_GUER),
			QGVAR(frag11_GUER),
			QGVAR(frag12_GUER),
			QGVAR(frag13_GUER),
			QGVAR(frag14_GUER)
		};
		smoke[] = {
			QGVAR(smoke01_GUER),
			QGVAR(smoke02_GUER),
			QGVAR(smoke03_GUER),
			QGVAR(smoke04_GUER),
			QGVAR(smoke05_GUER),
			QGVAR(smoke06_GUER),
			QGVAR(smoke07_GUER),
			QGVAR(smoke08_GUER),
			QGVAR(smoke09_GUER)
		};
		flash[] = {
			QGVAR(flash01_GUER),
			QGVAR(flash02_GUER),
			QGVAR(flash03_GUER),
			QGVAR(flash04_GUER),
			QGVAR(flash05_GUER),
			QGVAR(flash06_GUER),
			QGVAR(flash07_GUER)
		};
		incendiary[] = {
			QGVAR(incendiary01_GUER),
			QGVAR(incendiary02_GUER),
			QGVAR(incendiary03_GUER),
			QGVAR(incendiary04_GUER),
			QGVAR(incendiary05_GUER),
			QGVAR(incendiary06_GUER),
			QGVAR(incendiary07_GUER)
		};
		explosive[] = {
			QGVAR(explosive01_GUER),
			QGVAR(explosive02_GUER),
			QGVAR(explosive03_GUER),
			QGVAR(explosive04_GUER),
			QGVAR(explosive05_GUER),
			QGVAR(explosive06_GUER),
			QGVAR(explosive07_GUER),
			QGVAR(explosive08_GUER),
			QGVAR(explosive09_GUER),
			QGVAR(explosive10_GUER),
			QGVAR(explosive11_GUER),
			QGVAR(explosive12_GUER),
			QGVAR(explosive13_GUER),
			QGVAR(explosive14_GUER),
			QGVAR(explosive15_GUER),
			QGVAR(explosive16_GUER),
			QGVAR(explosive17_GUER)
		};
		spotNade[] = {
			QGVAR(spotNade01_GUER),
			QGVAR(spotNade02_GUER),
			QGVAR(spotNade03_GUER),
			QGVAR(spotNade04_GUER),
			QGVAR(spotNade05_GUER),
			QGVAR(spotNade06_GUER),
			QGVAR(spotNade07_GUER),
			QGVAR(spotNade08_GUER),
			QGVAR(spotNade09_GUER),
			QGVAR(spotNade10_GUER),
			QGVAR(spotNade11_GUER),
			QGVAR(spotNade12_GUER),
			QGVAR(spotNade13_GUER),
			QGVAR(spotNade14_GUER),
			QGVAR(spotNade15_GUER),
			QGVAR(spotNade16_GUER),
			QGVAR(spotNade17_GUER),
			QGVAR(spotNade18_GUER)
		};
		friendlyFire[] = {
			QGVAR(friendlyFire01_GUER),
			QGVAR(friendlyFire02_GUER),
			QGVAR(friendlyFire03_GUER),
			QGVAR(friendlyFire04_GUER),
			QGVAR(friendlyFire05_GUER),
			QGVAR(friendlyFire06_GUER),
			QGVAR(friendlyFire07_GUER),
			QGVAR(friendlyFire08_GUER),
			QGVAR(friendlyFire09_GUER),
			QGVAR(friendlyFire10_GUER),
			QGVAR(friendlyFire11_GUER)
		};
		wounded[] = {
			QGVAR(wounded01_GUER),
			QGVAR(wounded02_GUER),
			QGVAR(wounded03_GUER),
			QGVAR(wounded04_GUER),
			QGVAR(wounded05_GUER),
			QGVAR(wounded06_GUER),
			QGVAR(wounded07_GUER),
			QGVAR(wounded08_GUER),
			QGVAR(wounded09_GUER),
			QGVAR(wounded10_GUER),
			QGVAR(wounded11_GUER),
			QGVAR(wounded12_GUER),
			QGVAR(wounded13_GUER),
			QGVAR(wounded14_GUER),
			QGVAR(wounded15_GUER),
			QGVAR(wounded16_GUER),
			QGVAR(wounded17_GUER),
			QGVAR(wounded18_GUER),
			QGVAR(wounded19_GUER),
			QGVAR(wounded20_GUER),
			QGVAR(wounded21_GUER),
			QGVAR(wounded22_GUER),
			QGVAR(wounded23_GUER),
			QGVAR(wounded24_GUER),
			QGVAR(wounded25_GUER),
			QGVAR(wounded26_GUER),
			QGVAR(wounded27_GUER),
			QGVAR(wounded28_GUER),
			QGVAR(wounded29_GUER),
			QGVAR(wounded30_GUER),
			QGVAR(wounded31_GUER),
			QGVAR(wounded32_GUER),
			QGVAR(wounded33_GUER),
			QGVAR(wounded34_GUER),
			QGVAR(wounded35_GUER),
			QGVAR(wounded36_GUER),
			QGVAR(wounded37_GUER),
			QGVAR(wounded38_GUER),
			QGVAR(wounded39_GUER),
			QGVAR(wounded40_GUER)
		};
		allyDown[] = {
			QGVAR(allyDown01_GUER),
			QGVAR(allyDown02_GUER),
			QGVAR(allyDown03_GUER),
			QGVAR(allyDown04_GUER),
			QGVAR(allyDown05_GUER),
			QGVAR(allyDown06_GUER),
			QGVAR(allyDown07_GUER),
			QGVAR(allyDown08_GUER),
			QGVAR(allyDown09_GUER),
			QGVAR(allyDown10_GUER),
			QGVAR(allyDown11_GUER),
			QGVAR(allyDown12_GUER),
			QGVAR(allyDown13_GUER),
			QGVAR(allyDown14_GUER),
			QGVAR(allyDown15_GUER),
			QGVAR(allyDown16_GUER),
			QGVAR(allyDown17_GUER),
			QGVAR(allyDown18_GUER),
			QGVAR(allyDown19_GUER),
			QGVAR(allyDown20_GUER),
			QGVAR(allyDown21_GUER),
			QGVAR(allyDown22_GUER),
			QGVAR(allyDown23_GUER),
			QGVAR(allyDown24_GUER),
			QGVAR(allyDown25_GUER),
			QGVAR(allyDown26_GUER),
			QGVAR(allyDown27_GUER)
		};
		targDownHi[] = {
			QGVAR(targDownHi01_GUER),
			QGVAR(targDownHi02_GUER),
			QGVAR(targDownHi03_GUER),
			QGVAR(targDownHi04_GUER),
			QGVAR(targDownHi05_GUER),
			QGVAR(targDownHi06_GUER),
			QGVAR(targDownHi07_GUER),
			QGVAR(targDownHi08_GUER),
			QGVAR(targDownHi09_GUER),
			QGVAR(targDownHi10_GUER)
		};
		targDownLo[] = {
			QGVAR(targDownLo01_GUER),
			QGVAR(targDownLo02_GUER),
			QGVAR(targDownLo03_GUER),
			QGVAR(targDownLo04_GUER),
			QGVAR(targDownLo05_GUER),
			QGVAR(targDownLo06_GUER),
			QGVAR(targDownLo07_GUER),
			QGVAR(targDownLo08_GUER),
			QGVAR(targDownLo09_GUER),
			QGVAR(targDownLo10_GUER)
		};
		cover[] = {
			QGVAR(cover01_GUER),
			QGVAR(cover02_GUER),
			QGVAR(cover03_GUER),
			QGVAR(cover04_GUER),
			QGVAR(cover05_GUER),
			QGVAR(cover06_GUER),
			QGVAR(cover07_GUER),
			QGVAR(cover08_GUER),
			QGVAR(cover09_GUER),
			QGVAR(cover10_GUER),
			QGVAR(cover11_GUER),
			QGVAR(cover12_GUER),
			QGVAR(cover13_GUER),
			QGVAR(cover14_GUER),
			QGVAR(cover15_GUER),
			QGVAR(cover16_GUER),
			QGVAR(cover17_GUER),
			QGVAR(cover18_GUER),
			QGVAR(cover19_GUER),
			QGVAR(cover20_GUER),
			QGVAR(cover21_GUER),
			QGVAR(cover22_GUER)
		};
		ammoLow[] = {
			QGVAR(ammolow01_GUER),
			QGVAR(ammolow02_GUER),
			QGVAR(ammolow03_GUER),
			QGVAR(ammolow04_GUER),
			QGVAR(ammolow05_GUER),
			QGVAR(ammolow06_GUER)
		};
		reloading[] = {
			QGVAR(reloading01_GUER),
			QGVAR(reloading02_GUER),
			QGVAR(reloading03_GUER),
			QGVAR(reloading04_GUER),
			QGVAR(reloading05_GUER),
			QGVAR(reloading06_GUER),
			QGVAR(reloading07_GUER),
			QGVAR(reloading08_GUER),
			QGVAR(reloading09_GUER),
			QGVAR(reloading10_GUER),
			QGVAR(reloading11_GUER),
			QGVAR(reloading12_GUER),
			QGVAR(reloading13_GUER),
			QGVAR(reloading14_GUER),
			QGVAR(reloading15_GUER),
			QGVAR(reloading16_GUER),
			QGVAR(reloading17_GUER),
			QGVAR(reloading18_GUER),
			QGVAR(reloading19_GUER),
			QGVAR(reloading20_GUER),
			QGVAR(reloading21_GUER),
			QGVAR(reloading22_GUER),
			QGVAR(reloading23_GUER),
			QGVAR(reloading24_GUER),
			QGVAR(reloading25_GUER),
			QGVAR(reloading26_GUER),
			QGVAR(reloading27_GUER),
			QGVAR(reloading28_GUER),
			QGVAR(reloading29_GUER),
			QGVAR(reloading30_GUER),
			QGVAR(reloading31_GUER),
			QGVAR(reloading32_GUER),
			QGVAR(reloading33_GUER),
			QGVAR(reloading34_GUER),
			QGVAR(reloading35_GUER),
			QGVAR(reloading36_GUER),
			QGVAR(reloading37_GUER),
			QGVAR(reloading38_GUER),
			QGVAR(reloading39_GUER)
		};
		rocketSuppression[] = {
			QGVAR(rpg01_GUER),
			QGVAR(rpg02_GUER),
			QGVAR(rpg03_GUER),
			QGVAR(rpg04_GUER),
			QGVAR(rpg05_GUER),
			QGVAR(rpg06_GUER),
			QGVAR(rpg07_GUER),
			QGVAR(rpg08_GUER),
			QGVAR(rpg09_GUER)
		};
		bulletSuppression[] = {
			QGVAR(suppressed01_GUER),
			QGVAR(suppressed02_GUER),
			QGVAR(suppressed03_GUER),
			QGVAR(suppressed04_GUER),
			QGVAR(suppressed05_GUER),
			QGVAR(suppressed06_GUER),
			QGVAR(suppressed07_GUER),
			QGVAR(suppressed08_GUER),
			QGVAR(suppressed09_GUER),
			QGVAR(suppressed10_GUER),
			QGVAR(suppressed11_GUER),
			QGVAR(suppressed12_GUER),
			QGVAR(suppressed13_GUER),
			QGVAR(suppressed14_GUER),
			QGVAR(suppressed15_GUER),
			QGVAR(suppressed16_GUER),
			QGVAR(suppressed17_GUER),
			QGVAR(suppressed18_GUER),
			QGVAR(suppressed19_GUER),
			QGVAR(suppressed20_GUER),
			QGVAR(suppressed21_GUER),
			QGVAR(suppressed22_GUER),
			QGVAR(suppressed23_GUER),
			QGVAR(suppressed24_GUER),
			QGVAR(suppressed25_GUER),
			QGVAR(suppressed26_GUER),
			QGVAR(suppressed27_GUER),
			QGVAR(suppressed28_GUER),
			QGVAR(suppressed29_GUER),
			QGVAR(suppressed30_GUER),
			QGVAR(suppressed31_GUER),
			QGVAR(suppressed32_GUER),
			QGVAR(suppressed33_GUER),
			QGVAR(suppressed34_GUER),
			QGVAR(suppressed35_GUER)
		};
		death[] = {};
	};
};
