class UVO_voice_EAST {
	name = "EAST";
	factions[] = {};

	class events {
		calloutsN[] = {
			QGVAR(calloutN01_EAST),
			QGVAR(calloutN02_EAST),
			QGVAR(calloutN03_EAST)
		};
		calloutsNE[] = {
			QGVAR(calloutNE01_EAST),
			QGVAR(calloutNE02_EAST),
			QGVAR(calloutNE03_EAST)
		};
		calloutsE[] = {
			QGVAR(calloutE01_EAST),
			QGVAR(calloutE02_EAST),
			QGVAR(calloutE03_EAST)
		};
		calloutsSE[] = {
			QGVAR(calloutSE01_EAST),
			QGVAR(calloutSE02_EAST),
			QGVAR(calloutSE03_EAST)
		};
		calloutsS[] = {
			QGVAR(calloutS01_EAST),
			QGVAR(calloutS02_EAST),
			QGVAR(calloutS03_EAST)
		};
		calloutsSW[] = {
			QGVAR(calloutSW01_EAST),
			QGVAR(calloutSW02_EAST),
			QGVAR(calloutSW03_EAST)
		};
		calloutsW[] = {
			QGVAR(calloutW01_EAST),
			QGVAR(calloutW02_EAST),
			QGVAR(calloutW03_EAST)
		};
		calloutsNW[] = {
			QGVAR(calloutNW01_EAST),
			QGVAR(calloutNW02_EAST),
			QGVAR(calloutNW03_EAST)
		};
		frag[] = {
			QGVAR(frag01_EAST),
			QGVAR(frag02_EAST),
			QGVAR(frag03_EAST),
			QGVAR(frag04_EAST),
			QGVAR(frag05_EAST),
			QGVAR(frag06_EAST),
			QGVAR(frag07_EAST),
			QGVAR(frag08_EAST),
			QGVAR(frag09_EAST),
			QGVAR(frag10_EAST),
			QGVAR(frag11_EAST),
			QGVAR(frag12_EAST),
			QGVAR(frag13_EAST),
			QGVAR(frag14_EAST)
		};
		smoke[] = {
			QGVAR(smoke01_EAST),
			QGVAR(smoke02_EAST),
			QGVAR(smoke03_EAST),
			QGVAR(smoke04_EAST),
			QGVAR(smoke05_EAST),
			QGVAR(smoke06_EAST),
			QGVAR(smoke07_EAST),
			QGVAR(smoke08_EAST),
			QGVAR(smoke09_EAST)
		};
		flash[] = {
			QGVAR(flash01_EAST),
			QGVAR(flash02_EAST),
			QGVAR(flash03_EAST),
			QGVAR(flash04_EAST),
			QGVAR(flash05_EAST),
			QGVAR(flash06_EAST),
			QGVAR(flash07_EAST)
		};
		incendiary[] = {
			QGVAR(incendiary01_EAST),
			QGVAR(incendiary02_EAST),
			QGVAR(incendiary03_EAST),
			QGVAR(incendiary04_EAST),
			QGVAR(incendiary05_EAST),
			QGVAR(incendiary06_EAST),
			QGVAR(incendiary07_EAST)
		};
		explosive[] = {
			QGVAR(explosive01_EAST),
			QGVAR(explosive02_EAST),
			QGVAR(explosive03_EAST),
			QGVAR(explosive04_EAST),
			QGVAR(explosive05_EAST),
			QGVAR(explosive06_EAST),
			QGVAR(explosive07_EAST),
			QGVAR(explosive08_EAST),
			QGVAR(explosive09_EAST),
			QGVAR(explosive10_EAST),
			QGVAR(explosive11_EAST),
			QGVAR(explosive12_EAST),
			QGVAR(explosive13_EAST),
			QGVAR(explosive14_EAST),
			QGVAR(explosive15_EAST),
			QGVAR(explosive16_EAST),
			QGVAR(explosive17_EAST)
		};
		spotNade[] = {
			QGVAR(spotNade01_EAST),
			QGVAR(spotNade02_EAST),
			QGVAR(spotNade03_EAST),
			QGVAR(spotNade04_EAST),
			QGVAR(spotNade05_EAST),
			QGVAR(spotNade06_EAST),
			QGVAR(spotNade07_EAST),
			QGVAR(spotNade08_EAST),
			QGVAR(spotNade09_EAST),
			QGVAR(spotNade10_EAST),
			QGVAR(spotNade11_EAST),
			QGVAR(spotNade12_EAST),
			QGVAR(spotNade13_EAST),
			QGVAR(spotNade14_EAST),
			QGVAR(spotNade15_EAST),
			QGVAR(spotNade16_EAST),
			QGVAR(spotNade17_EAST),
			QGVAR(spotNade18_EAST),
			QGVAR(spotNade19_EAST),
			QGVAR(spotNade20_EAST),
			QGVAR(spotNade21_EAST),
			QGVAR(spotNade22_EAST),
			QGVAR(spotNade23_EAST)
		};
		friendlyFire[] = {
			QGVAR(friendlyFire01_EAST),
			QGVAR(friendlyFire02_EAST),
			QGVAR(friendlyFire03_EAST),
			QGVAR(friendlyFire04_EAST),
			QGVAR(friendlyFire05_EAST),
			QGVAR(friendlyFire06_EAST),
			QGVAR(friendlyFire07_EAST),
			QGVAR(friendlyFire08_EAST),
			QGVAR(friendlyFire09_EAST),
			QGVAR(friendlyFire10_EAST),
			QGVAR(friendlyFire11_EAST),
			QGVAR(friendlyFire12_EAST),
			QGVAR(friendlyFire13_EAST),
			QGVAR(friendlyFire14_EAST)
		};
		wounded[] = {
			QGVAR(wounded01_EAST),
			QGVAR(wounded02_EAST),
			QGVAR(wounded03_EAST),
			QGVAR(wounded04_EAST),
			QGVAR(wounded05_EAST),
			QGVAR(wounded06_EAST),
			QGVAR(wounded07_EAST),
			QGVAR(wounded08_EAST),
			QGVAR(wounded09_EAST),
			QGVAR(wounded10_EAST),
			QGVAR(wounded11_EAST),
			QGVAR(wounded12_EAST),
			QGVAR(wounded13_EAST),
			QGVAR(wounded14_EAST),
			QGVAR(wounded15_EAST),
			QGVAR(wounded16_EAST),
			QGVAR(wounded17_EAST),
			QGVAR(wounded18_EAST),
			QGVAR(wounded19_EAST),
			QGVAR(wounded20_EAST),
			QGVAR(wounded21_EAST),
			QGVAR(wounded22_EAST),
			QGVAR(wounded23_EAST),
			QGVAR(wounded24_EAST),
			QGVAR(wounded25_EAST),
			QGVAR(wounded26_EAST),
			QGVAR(wounded27_EAST),
			QGVAR(wounded28_EAST),
			QGVAR(wounded29_EAST),
			QGVAR(wounded30_EAST),
			QGVAR(wounded31_EAST),
			QGVAR(wounded32_EAST),
			QGVAR(wounded33_EAST),
			QGVAR(wounded34_EAST),
			QGVAR(wounded35_EAST),
			QGVAR(wounded36_EAST),
			QGVAR(wounded37_EAST),
			QGVAR(wounded38_EAST),
			QGVAR(wounded39_EAST),
			QGVAR(wounded40_EAST)
		};
		allyDown[] = {
			QGVAR(allyDown01_EAST),
			QGVAR(allyDown02_EAST),
			QGVAR(allyDown03_EAST),
			QGVAR(allyDown04_EAST),
			QGVAR(allyDown05_EAST),
			QGVAR(allyDown06_EAST),
			QGVAR(allyDown07_EAST),
			QGVAR(allyDown08_EAST),
			QGVAR(allyDown09_EAST),
			QGVAR(allyDown10_EAST),
			QGVAR(allyDown11_EAST),
			QGVAR(allyDown12_EAST),
			QGVAR(allyDown13_EAST),
			QGVAR(allyDown14_EAST),
			QGVAR(allyDown15_EAST),
			QGVAR(allyDown16_EAST),
			QGVAR(allyDown17_EAST),
			QGVAR(allyDown18_EAST),
			QGVAR(allyDown19_EAST),
			QGVAR(allyDown20_EAST),
			QGVAR(allyDown21_EAST),
			QGVAR(allyDown22_EAST),
			QGVAR(allyDown23_EAST),
			QGVAR(allyDown24_EAST),
			QGVAR(allyDown25_EAST),
			QGVAR(allyDown26_EAST)
		};
		targDownHi[] = {
			QGVAR(targDownHi01_EAST),
			QGVAR(targDownHi02_EAST),
			QGVAR(targDownHi03_EAST),
			QGVAR(targDownHi04_EAST),
			QGVAR(targDownHi05_EAST),
			QGVAR(targDownHi06_EAST),
			QGVAR(targDownHi07_EAST),
			QGVAR(targDownHi08_EAST),
			QGVAR(targDownHi09_EAST),
			QGVAR(targDownHi10_EAST)
		};
		targDownLo[] = {
			QGVAR(targDownLo01_EAST),
			QGVAR(targDownLo02_EAST),
			QGVAR(targDownLo03_EAST),
			QGVAR(targDownLo04_EAST),
			QGVAR(targDownLo05_EAST),
			QGVAR(targDownLo06_EAST),
			QGVAR(targDownLo07_EAST),
			QGVAR(targDownLo08_EAST),
			QGVAR(targDownLo09_EAST),
			QGVAR(targDownLo10_EAST)
		};
		cover[] = {
			QGVAR(cover01_EAST),
			QGVAR(cover02_EAST),
			QGVAR(cover03_EAST),
			QGVAR(cover04_EAST),
			QGVAR(cover05_EAST),
			QGVAR(cover06_EAST),
			QGVAR(cover07_EAST),
			QGVAR(cover08_EAST),
			QGVAR(cover09_EAST),
			QGVAR(cover10_EAST),
			QGVAR(cover11_EAST),
			QGVAR(cover12_EAST),
			QGVAR(cover13_EAST),
			QGVAR(cover14_EAST),
			QGVAR(cover15_EAST),
			QGVAR(cover16_EAST),
			QGVAR(cover17_EAST),
			QGVAR(cover18_EAST)
		};
		ammoLow[] = {
			QGVAR(ammolow01_EAST),
			QGVAR(ammolow02_EAST),
			QGVAR(ammolow03_EAST),
			QGVAR(ammolow04_EAST),
			QGVAR(ammolow05_EAST),
			QGVAR(ammolow06_EAST)
		};
		reloading[] = {
			QGVAR(reloading01_EAST),
			QGVAR(reloading02_EAST),
			QGVAR(reloading03_EAST),
			QGVAR(reloading04_EAST),
			QGVAR(reloading05_EAST),
			QGVAR(reloading06_EAST),
			QGVAR(reloading07_EAST),
			QGVAR(reloading08_EAST),
			QGVAR(reloading09_EAST),
			QGVAR(reloading10_EAST),
			QGVAR(reloading11_EAST),
			QGVAR(reloading12_EAST),
			QGVAR(reloading13_EAST),
			QGVAR(reloading14_EAST),
			QGVAR(reloading15_EAST),
			QGVAR(reloading16_EAST),
			QGVAR(reloading17_EAST),
			QGVAR(reloading18_EAST),
			QGVAR(reloading19_EAST),
			QGVAR(reloading20_EAST),
			QGVAR(reloading21_EAST),
			QGVAR(reloading22_EAST),
			QGVAR(reloading23_EAST),
			QGVAR(reloading24_EAST),
			QGVAR(reloading25_EAST),
			QGVAR(reloading26_EAST),
			QGVAR(reloading27_EAST),
			QGVAR(reloading28_EAST),
			QGVAR(reloading29_EAST),
			QGVAR(reloading30_EAST),
			QGVAR(reloading31_EAST),
			QGVAR(reloading32_EAST),
			QGVAR(reloading33_EAST),
			QGVAR(reloading34_EAST),
			QGVAR(reloading35_EAST),
			QGVAR(reloading36_EAST),
			QGVAR(reloading37_EAST),
			QGVAR(reloading38_EAST),
			QGVAR(reloading39_EAST)
		};
		rocketSuppression[] = {
			QGVAR(rpg01_EAST),
			QGVAR(rpg02_EAST),
			QGVAR(rpg03_EAST),
			QGVAR(rpg04_EAST),
			QGVAR(rpg05_EAST),
			QGVAR(rpg06_EAST),
			QGVAR(rpg07_EAST),
			QGVAR(rpg08_EAST),
			QGVAR(rpg09_EAST)
		};
		bulletSuppression[] = {
			QGVAR(suppressed01_EAST),
			QGVAR(suppressed02_EAST),
			QGVAR(suppressed03_EAST),
			QGVAR(suppressed04_EAST),
			QGVAR(suppressed05_EAST),
			QGVAR(suppressed06_EAST),
			QGVAR(suppressed07_EAST),
			QGVAR(suppressed08_EAST),
			QGVAR(suppressed09_EAST),
			QGVAR(suppressed10_EAST),
			QGVAR(suppressed11_EAST),
			QGVAR(suppressed12_EAST),
			QGVAR(suppressed13_EAST),
			QGVAR(suppressed14_EAST),
			QGVAR(suppressed15_EAST),
			QGVAR(suppressed16_EAST),
			QGVAR(suppressed17_EAST),
			QGVAR(suppressed18_EAST),
			QGVAR(suppressed19_EAST),
			QGVAR(suppressed20_EAST),
			QGVAR(suppressed21_EAST),
			QGVAR(suppressed22_EAST),
			QGVAR(suppressed23_EAST),
			QGVAR(suppressed24_EAST),
			QGVAR(suppressed25_EAST),
			QGVAR(suppressed26_EAST),
			QGVAR(suppressed27_EAST),
			QGVAR(suppressed28_EAST),
			QGVAR(suppressed29_EAST),
			QGVAR(suppressed30_EAST),
			QGVAR(suppressed31_EAST),
			QGVAR(suppressed32_EAST),
			QGVAR(suppressed33_EAST),
			QGVAR(suppressed34_EAST),
			QGVAR(suppressed35_EAST),
			QGVAR(suppressed36_EAST)
		};
		death[] = {};
	};
};
