class UVO_voice_common {
	name = "common";
	factions[] = {};

	class events {
		death[] = {
			QGVAR(death01),
			QGVAR(death02),
			QGVAR(death03),
			QGVAR(death04),
			QGVAR(death05),
			QGVAR(death06),
			QGVAR(death07),
			QGVAR(death08),
			QGVAR(death09),
			QGVAR(death10),
			QGVAR(death11),
			QGVAR(death12),
			QGVAR(death13),
			QGVAR(death14),
			QGVAR(death15),
			QGVAR(death16),
			QGVAR(death17),
			QGVAR(death18),
			QGVAR(death19),
			QGVAR(death20),
			QGVAR(death21),
			QGVAR(death22),
			QGVAR(death23),
			QGVAR(death24),
			QGVAR(death25),
			QGVAR(death26),
			QGVAR(death27),
			QGVAR(death28),
			QGVAR(death29),
			QGVAR(death30),
			QGVAR(death31),
			QGVAR(death32),
			QGVAR(death33),
			QGVAR(death34),
			QGVAR(death35),
			QGVAR(death36),
			QGVAR(death37),
			QGVAR(death38),
			QGVAR(death39),
			QGVAR(death40),
			QGVAR(death41),
			QGVAR(death42),
			QGVAR(death43),
			QGVAR(death44),
			QGVAR(death45),
			QGVAR(death46),
			QGVAR(death47),
			QGVAR(death48),
			QGVAR(death49),
			QGVAR(death50),
			QGVAR(death51),
			QGVAR(death52)
		};
	};
};
