GVAR(throwablesHash) = createHashMapFromArray [
	// 1: frag
	["handgrenade",1],
	["minigrenade",1],
	["rhs_mag_rgd5",1],
	["rhs_mag_rgn",1],
	["rhs_mag_rgo",1],
	["rhs_mag_f1",1],
	["rhs_mag_m67",1],
	["rhs_mag_m69",1],

	// 2: smoke
	["smokeshellorange",2],
	["smokeshellblue",2],
	["smokeshellpurple",2],
	["smokeshellyellow",2],
	["smokeshellgreen",2],
	["smokeshellred",2],
	["smokeshell",2],
	["rhs_mag_rdg2_white",2],
	["rhs_mag_rdg2_black",2],
	["rhs_mag_nspd",2],
	["rhs_mag_an_m8hc",2],
	["rhs_mag_m18_green",2],
	["rhs_mag_m18_red",2],
	["rhs_mag_m18_yellow",2],
	["rhs_mag_m18_purple",2],

	// 3: flash
	["ace_m84",3],
	["rhs_mag_fakel",3],
	["rhs_mag_fakels",3],
	["rhs_mag_zarya2",3],
	["rhs_mag_plamyam",3],
	["rhs_mag_mk84",3],
	["rhs_mag_m7a3_cs",3],

	// 4: incendiary
	["ace_m14",4],
	["rhs_mag_mk3a2",4],
	["rhs_mag_an_m14_th3",4],

	// 5: explosive
	["rhsgref_mag_rkg3em",5],
	["rhsusf_m112_mag",5],
	["rhsusf_m112x4_mag",5],
	["rhsusf_mine_m14_mag",5],
	["rhs_mine_m19_mag",5],
	["rhssaf_mine_mrud_c_mag",5],
	["rhssaf_mine_mrud_a_mag",5],
	["rhssaf_mine_mrud_b_mag",5],
	["rhssaf_mine_mrud_d_mag",5],
	["rhs_mag_mine_pfm1",5],
	["rhs_mine_pmn2_mag",5],
	["rhs_mag_mine_ptm1",5],
	["rhs_mine_tm62m_mag",5],
	["rhssaf_mine_tma4_mag",5],
	["rhssaf_mine_pma3_mag",5],
	["satchelcharge_remote_mag",5],
	["democharge_remote_mag",5],
	["atmine_range_mag",5],
	["apersmine_range_mag",5],
	["apersboundingmine_range_mag",5],
	["slamdirectionalmine_wire_mag",5],
	["aperstripmine_wire_mag",5],
	["claymoredirectionalmine_remote_mag",5],
	["iedurbanbig_remote_mag",5],
	["iedlandbig_remote_mag",5],
	["iedurbansmall_remote_mag",5],
	["iedlandsmall_remote_mag",5]
];
